name: matching-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 194418667391.dkr.ecr.ap-south-1.amazonaws.com/medicojob-matching-service
  tag: d7010cefbee5ab043bace645190ab23fa0980e63
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5003
  targetPort: 5003
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
env:
  PORT: "5003"
probes:
  readiness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: null
    periodSeconds: 10
  liveness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: null
    periodSeconds: 20
resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
