name: job-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 168614391879.dkr.ecr.ap-south-1.amazonaws.com/medicojob-job-service
  tag: 238806d6bb0e67b8cc00264d36474f2c7a293a00
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5002
  targetPort: 5002
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
probes:
  readiness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 45
    periodSeconds: 20
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi
