name: job-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 194418667391.dkr.ecr.ap-south-1.amazonaws.com/medicojob-job-service
  tag: cdced7870efc98c31fc23c4129e77c2731b180a7
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5002
  targetPort: 5002
serviceAccount:
  create: true
  name: job-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::194418667391:role/medicojobs-cluster-workload-irsa
env:
  PORT: "5002"
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
probes:
  readiness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 45
    periodSeconds: 20
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi
