name: reputation-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 168614391879.dkr.ecr.ap-south-1.amazonaws.com/medicojob-reputation-service
  tag: 58b25e2009ccbb8d682d2d657a443e0a666078ae
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5006
  targetPort: 5006
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
env:
  PORT: "5006"
  NODE_OPTIONS: "--unhandled-rejections=warn"
probes:
  readiness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: null
    periodSeconds: 10
  liveness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: null
    periodSeconds: 20
resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
