name: user-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 168614391879.dkr.ecr.ap-south-1.amazonaws.com/medicojob-user-service
  tag: 14a6a42aba3460551b884a1ba2e8a6ed635844d5
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5001
  targetPort: 5001
serviceAccount:
  create: true
  name: user-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::168614391879:role/medicojobs-cluster-workload-irsa
env:
  PORT: "5001"
  CORS_ORIGINS: "http://medicojobs.online,http://www.medicojobs.online"
  DYNAMODB_USERS_TABLE: "medicojobs-users"
  AWS_S3_BUCKET: "medicojobs-cluster-uploads-168614391879"
  S3_PROFILE_IMAGES_PREFIX: "profile-images"
  S3_RESUMES_PREFIX: "resume-pdfs"
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
probes:
  readiness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    enabled: true
    type: tcp
    path: /health
    initialDelaySeconds: 45
    periodSeconds: 20
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi
