name: resume-service
namespace: medicojobs-prod
replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: 168614391879.dkr.ecr.ap-south-1.amazonaws.com/medicojob-resume-service
  tag: fc969e205aefaa1a54c522a185cefcedb424f2f9
  pullPolicy: IfNotPresent
strategy:
  maxUnavailable: 1
  maxSurge: 0
service:
  type: ClusterIP
  port: 5008
  targetPort: 5008
envFrom:
  enabled: true
  configMapName: medicojobs-config
  secretName: medicojobs-secrets
probes:
  readiness:
    enabled: true
    type: http
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    enabled: true
    type: http
    path: /health
    initialDelaySeconds: 60
    periodSeconds: 20
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1500m
    memory: 2Gi
